// Generated by sync_website_contacts.py; edit the brand source, not this file.
// Source: references/brands/STUDIOLEE_BRAND.md # Primary contact
export const publicContacts = {
  "primary": {
    "email": "tim@studiolee.nl"
  }
} as const;
